import iconAdvantage from 'src/assets/advantage';
import imgCandidate from 'src/assets/candidates';
import imgCustomer from 'src/assets/customers';
import imgBadge from 'src/assets/badges';
import imgService from 'src/assets/services';

import { QuoteStep, CarSelectType } from 'src/types';

export const integrations = [
  {
    logo: '/images/logos/slack.svg',
    name: 'Slack',
  },
  {
    logo: '/images/logos/mailchimp.svg',
    name: 'Mailchimp',
  },
  {
    logo: '/images/logos/dropbox.svg',
    name: 'Dropbox',
  },
  {
    logo: '/images/logos/google-drive.svg',
    name: 'Google Drive',
  },
  {
    logo: '/images/logos/google-ad-manager.svg',
    name: 'Google Ad Manager',
  },
  {
    logo: '/images/logos/atlassian.svg',
    name: 'Atlassian',
  },
];

export const advantageCompareList = {
  FIXMYCAR: 'Fixmycar',
  REPAIR_SHOP: 'Repair Shop',
};

export const itemsAdvantage = [
  {
    img: iconAdvantage.money,
    title: 'Affordable & honest',
    subtitle:
      "Fixed & upfront pricing. No hidden fees and you'll get the lowest prices guaranteed.",
  },
  {
    img: iconAdvantage.ring,
    title: "We'll come to you",
    subtitle:
      'Friendly, car mechanics will come to your home, office or parking lot.',
  },
  {
    img: iconAdvantage.time,
    title: 'Flexible hours',
    subtitle:
      'Open every-day from 9am - 9pm. Book our epxerienced certified technicians today.',
  },
];

export const itemsShop = [
  {
    img: iconAdvantage.shop_money,
    title: 'Expensive & devius',
    subtitle: '30% more expensive and come with additional fees & upsells.',
  },
  {
    img: iconAdvantage.shop_location,
    title: 'Inconvinient service locations',
    subtitle: 'Repairs must be done at a physical auto repair shop.',
  },
  {
    img: iconAdvantage.shop_rigid,
    title: 'Rigid hours',
    subtitle: 'Open limited hours and at times closed on weekends.',
  },
];

export const itemsCustomer = [
  {
    img: imgCustomer.mariah,
    name: 'Mariah Heighl',
  },
  {
    img: imgCustomer.johnny,
    name: 'Johnny Riece',
  },
  {
    img: imgCustomer.marian,
    name: 'Marian Huves',
  },
  {
    img: imgCustomer.alice,
    name: 'Alice Bleu',
  },
];

export const itemsLocation = [
  {
    state: 'Michigan',
    description: 'Metro Detroit',
    city: [
      'Detroit',
      'Sterling Heights',
      'Warren',
      'Ann Arbor',
      'Dearborn',
      'Livonia',
      'Detroitt',
      'Sterling Heightst',
      'Warrent',
      'Ann Arbort',
      'Dearbornt',
      'Livoniat',
      'Detroitr',
      'Sterling Heightsr',
      'Warrenr',
      'Ann Arborr',
      'Dearbornr',
      'Livoniar',
      'Detroite',
      'Sterling Heightsa',
      'Warrenq',
    ],
  },
  {
    state: 'Texas',
    description: 'Dallas Fort Worth & Houston',
    city: [
      'Detroit',
      'Sterling Heights',
      'Warren',
      'Ann Arbor',
      'Dearborn',
      'Livonia',
      'Detroitt',
      'Sterling Heightst',
      'Warrent',
      'Ann Arbort',
      'Dearbornt',
      'Livoniat',
      'Detroitr',
      'Sterling Heightsr',
      'Warrenr',
      'Ann Arborr',
      'Dearbornr',
      'Livoniar',
      'Detroite',
      'Sterling Heightsa',
      'Warrene',
    ],
  },
];

export const itemsCandidates = [
  {
    name: 'Steve Gerrard',
    photo: imgCandidate.steven,
    photoASE: 'steven-ase.png',
    rating: 5,
    review: 106,
    bio:
      'I have a Master Certification and I pride on good work. Really enjoy working on cars',
    mention: [
      '22 years of experience',
      'Background checked',
      "Passed FixMyCar's test",
    ],
    badge: [
      {
        name: 'Brakes',
        img: imgBadge.brakes,
      },
      {
        name: 'Suspension',
        img: imgBadge.suspension,
      },
      {
        name: 'Engine',
        img: imgBadge.engine,
      },
      {
        name: 'Electrical',
        img: imgBadge.electrical,
      },
      {
        name: 'Diagnosis',
        img: imgBadge.diagnosis,
      },
      {
        name: 'European Cars',
        img: imgBadge.european_cars,
      },
    ],
  },
  {
    name: 'Mark Zuckerberg',
    photo: imgCandidate.mark,
    rating: 5,
    review: 106,
    bio:
      'I have a Master Certification and I pride on good work. Really enjoy working on cars',
    mention: [
      '22 years of experience',
      'Background checked',
      "Passed FixMyCar's test",
    ],
    badge: [
      {
        name: 'Brakes',
        img: imgBadge.brakes,
      },
      {
        name: 'Suspension',
        img: imgBadge.suspension,
      },
      {
        name: 'Engine',
        img: imgBadge.engine,
      },
      {
        name: 'Electrical',
        img: imgBadge.electrical,
      },
      {
        name: 'Diagnosis',
        img: imgBadge.diagnosis,
      },
      {
        name: 'European Cars',
        img: imgBadge.european_cars,
      },
    ],
  },
];

export const itemFooter = {
  menu: ['Services', 'Advice', 'Help'],
  carMakers: [
    'Acura',
    'Aston Martin',
    'Bentley',
    'Cadilac',
    'Ferrari',
    'Infinity',
    'Lexus',
    'Lincoin',
    'Maserati',
    'Maybach',
    'Mazda',
    'Mercury',
    'Mini',
    'Bmw',
    'Buick',
    'Hummer',
    'Acurat',
    'Aston Martint',
    'Bentleyt',
    'Cadilact',
    'Ferrarit',
    'Infinityt',
    'Lexust',
    'Lincoint',
    'Maseratit',
    'Maybacht',
    'Mazdat',
    'Mercuryt',
    'Minit',
    'Bmwt',
    'Buickt',
    'Hummert',
    'Acurar',
    'Aston Martinr',
    'Bentleyr',
    'Cadilacr',
    'Ferrarir',
    'Infinityr',
    'Lexusr',
    'Lincoinr',
    'Maseratir',
    'Maybachr',
    'Mazdar',
    'Mercuryr',
    'Minir',
    'Bmwr',
    'Buickr',
    'Hummerr',
  ],
};

// quote variables
export const stateList = [
  'AK',
  'AL',
  'AR',
  'AS',
  'AZ',
  'CA',
  'CO',
  'CT',
  'DC',
  'DE',
  'FL',
  'GA',
  'GU',
  'HI',
  'IA',
  'ID',
  'IL',
  'IN',
  'KS',
  'KY',
  'LA',
  'MA',
  'MD',
  'ME',
  'MI',
  'MN',
  'MO',
  'MS',
  'MT',
  'NC',
  'ND',
  'NE',
  'NH',
  'NJ',
  'NM',
  'NV',
  'NY',
  'OH',
  'OK',
  'OR',
  'PA',
  'PR',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VA',
  'VI',
  'VT',
  'WA',
  'WI',
  'WV',
  'WY',
];

export const arrCarSelectTypes = {
  [CarSelectType.BY_YEAR_MAKE_MODEL]: 'Year/make/model',
  [CarSelectType.BY_PLATE_NUMBER]: 'Plate number',
};

export const arrQuoteSteps = [
  QuoteStep.QUOTE_SERVICE_DESK,
  QuoteStep.QUOTE_SEARCH_CAR,
  QuoteStep.QUOTE_CONTACT,
];

export const allBrands = {
  Audi: 'Audi',
  Ford: 'Ford',
  Benz: 'Benz',
};

export const allModels = {
  V3: 'V3',
  MM1: 'MM1',
  H123: 'H123',
};

export const allMotors = {
  V3: 'V3',
  MM1: 'MM1',
  H123: 'H123',
};

export const allMileage = [
  'less than 50,000',
  '50,000 - 75,000',
  '75,000 -  100,000',
  '100,000 - 150,000',
  'more than 150,000',
];

export const allStaticServices = [
  {
    name: 'Front brakes pads & rotors',
    image: imgService.brakes,
    imageSelected: imgService.brakes_selected,
  },
  {
    name: 'Used car',
    image: imgService.used_car,
    imageSelected: imgService.used_car_selected,
  },
  {
    name: 'Diagnosis / Inspection',
    image: imgService.diagnosis,
    imageSelected: imgService.diagnosis_selected,
  },
  {
    name: 'Oil Change',
    image: imgService.oil_change,
    imageSelected: imgService.oil_change_selected,
  },
  {
    name: 'Replace Starter',
    image: imgService.replace_starter,
    imageSelected: imgService.replace_starter_selected,
  },
  {
    name: 'Replace Battery',
    image: imgService.replace_battery,
    imageSelected: imgService.replace_battery_selected,
  },
];

export const listNotSureReasons = [
  {
    id: 1,
    title: 'I hear something',
    subReason: [
      'Knocking/clunking sound',
      'Whining sound',
      'Squealing sound',
      'Grinding sound',
      'Rattling sound',
      'Humming sound',
      'Starting trouble',
      'Loud noise',
    ],
  },
  {
    id: 2,
    title: 'I smell something',
    subReason: [
      'Burning smell',
      'Musty, stale odor',
      'Rotten eggs',
      'Coolant',
      'Fuel',
    ],
  },
  {
    id: 3,
    title: 'I feel something',
    subReason: [
      'AC blowing hot air',
      'Car stalling',
      'Drifts or pulls to the side',
      'Car is vibrating',
      'Poor acceleration',
      'Poor shifting',
      'Steering has excessive play',
      'Poor braking',
      'Rough idling',
      'Suspension feels uneven',
      'Car is jerking',
    ],
  },
  {
    id: 4,
    title: 'I see something',
    subReason: [
      'Fluid leaking',
      'Warning light on',
      'Smoke',
      'Poor gas mileage',
      'Uneven tire wear',
      'No electrical power',
    ],
  },
  {
    id: 5,
    title: 'Warning light',
    subReason: [
      'Battery Light',
      'Check Engine Light',
      'Low Engine Oil Light',
      'Engine Temperature Light',
      'ABS Warning Light',
      'Brake Warning Light',
      'Air Bag Light',
    ],
  },
  {
    id: 6,
    title: 'Starting trouble',
    subReason: ['Sounds rough', 'Hard to start'],
  },
  {
    id: 7,
    title: 'Failed smog check',
    subReason: [],
  },
  {
    id: 8,
    title: 'Car is dead',
    subReason: [],
  },
];

export const faq = [
  {
    q: 'Does the inspection include the travel fee?',
    a:
      'The insepction service includes all the travel fees. The fixed price you get, is the fixed price you pay.',
  },
  {
    q: 'How long does it take for a tech to contact me?',
    a:
      'The insepction service includes all the travel fees. The fixed price you get, is the fixed price you pay.',
  },
  {
    q: 'If a tech cannot find me, will they call?',
    a:
      'The insepction service includes all the travel fees. The fixed price you get, is the fixed price you pay.',
  },
  {
    q: 'If my car cannot be fixed, what happens?',
    a:
      'The insepction service includes all the travel fees. The fixed price you get, is the fixed price you pay.',
  },
  {
    q: 'May I use the same tech in the future?',
    a:
      'The insepction service includes all the travel fees. The fixed price you get, is the fixed price you pay.',
  },
  {
    q: 'What if I find a cheaper alternative?',
    a:
      'The insepction service includes all the travel fees. The fixed price you get, is the fixed price you pay.',
  },
];

export const carLocations = [
  'Driveway',
  'Business Parking Lot',
  'Apartment Parking Lot',
  'Street Parking',
  'Other',
];

export const cardTypes = ['visa', 'mastercard', 'american-express'];

export const staticServiceList = [
  'Auxiliary Battery Replacement',
  'Positive Battery Cable Replacement',
  'Negative Battery Cable Replacement',
  'Battery Replacement',
  'Replace Battery/Cables',
  'Car AC Belt Replacement',
  'Alternator Replacement',
  'Alternator / Serpentine Belt Replacement',
  'Drive Belt Tensioner Replacement',
  'Front Brake Pad Replacement',
  'Rear Brake Pad Replacement',
  'Front & Rear Brake Pad Replacement',
  'Front Brake Rotors/Discs Replacement',
  'Rear Brake Rotors/Discs Replacement',
  'Front & Rear Brake Rotors/Discs Replacement',
  'Anti Lock Control Relay Replacement',
  'Front Brake Caliper Replacement',
  'Rear Brake Caliper Replacement',
  'Front and Rear Brake Caliper Replacement',
  'Front Brake Drum Replacement',
  'Rear Brake Drum Replacement',
  'Front and Rear Brake Drum Replacement',
  'Brake Master Cylinder Replacement',
  'Rear Brake Shoe Replacement',
  'Brake Vacuum Pump Replacement',
  'Brake Wheel Cylinder Replacement',
  'Emergency/Parking Brake Cable Replacement',
  'Emergency/Parking Brake Shoe Replacement',
  'Emergency Brake Control Replacement',
  'Parking Brake Release Cable Replacement',
  'Vacuum Brake Booster Check Valve Replacement',
  'Vacuum Pump Repair',
  'Front Wheel Hub Assembly Replacement (Both Sides)',
  'Rear Wheel Hub Assembly Replacement (Both Sides)',
  'Front & Rear Wheel Hub Assembly Replacement (Both Sides)',
  'Front Wheel Speed Sensor Replacement (One Side)',
  'Front Wheel Speed Sensor Replacement (Both Sides)',
  'Rear Wheel Speed Sensor Replacement (One Side)',
  'Rear Wheel Speed Sensor Replacement (Both Sides)',
  'Front & Rear Wheel Speed Sensors Replacement (Both Sides)',
  'Purchase Inspection',
  'Axle Shaft Seal Replacement',
  'Clutch Cable Replacement',
  'Differential Gasket Replacement',
  'Differential Output Seal Replacement',
  'Flexible Clutch Hose Replacement',
  'Shift Interlock Solenoid Replacement',
  'Shift Selector Cable Replacement',
  'Shifter Interlock Solenoid Replacement',
  'Speed Sensor Replacement',
  'Speedometer Cable Repair',
  'Transmission Oil Pressure Switch Replacement',
  'Transmission Position Sensor (Switch) Replacement',
  'Transmission Speed Sensor Replacement',
  '50-Point Inspection',
  'Abs Light is On Inspection',
  'Adjust Windshield Washer Jets',
  'Banging Noises When Driving Over The Bumps Inspection',
  'Battery Light is On Inspection',
  'Battery is Dead Inspection',
  'Battery Will Not Hold A Charge Inspection',
  'Brake Pedal is Hard To Push Inspection',
  'Brake Pedal Vibrates Or Shakes Inspection',
  'Brake Warning Light is On Inspection',
  'Brake Fluid is Black Or Brown Inspection',
  'Brake Fluid is Leaking Inspection',
  'Brake Fluid is Leaking Around Clutch Pedal Inspection',
  'Brake Light is Not Working Inspection',
  'Brake Pads Are Wearing Out Quickly Inspection',
  'Brake Pedal is Lower Than Usual Inspection',
  'Brake Pedal is Pulsating Inspection',
  'Brake Pedal is Spongy Inspection',
  'Brake Pressure is Uneven Inspection',
  'Brake Rotors Are Turning Blue Inspection',
  'Brake Safety Inspection',
  'Brakes Must Be Pumped To Work Inspection',
  'Brakes, Steering and Suspension Inspection',
  'Car Does Not Move When I Step On The Gas Pedal Inspection',
  'Car Does Not Shift From Park To Drive Inspection',
  'Car Has Bouncy and Unstable Ride Inspection',
  'Car Has Excessive Body Roll Inspection',
  'Car Idle is Rough Inspection',
  'Car is Hard To Shift Inspection',
  'Car is Hard To Start Inspection',
  'Car is Hesitating and Bucking Inspection',
  'Car is Leaning To One Side Inspection',
  'Car is Making A Noise Inspection',
  'Car is Not Getting Enough Power Inspection',
  'Car is Not Shifting Into Park Inspection',
  'Car is Not Starting Inspection',
  'Car is Overheating Inspection',
  'Car is Running Hotter Than Normal Inspection',
  'Car is Shaking Or Vibrating Inspection',
  'Car is Slow To Accelerate Inspection',
  'Car is Stalling Inspection',
  'Car is Taking Longer Than Normal To Stop Inspection',
  'Car Nose Dives When Braking Inspection',
  'Car Overheats Quickly Inspection',
  'Car Shudders When Turning Inspection',
  'Car Shuts off When Stepping On Gas Pedal Inspection',
  'Car Starts and Then Dies Inspection',
  'Car Surges When Air Conditioning is On Inspection',
  'Car Vibrates Going Uphill Inspection',
  'Car Will Not Turn Over Inspection',
  'Check Engine Light is On Inspection',
  'Check Fuel Cap Light is On Inspection',
  'Clear Fluid is Leaking Inspection',
  'Clicking Or Popping Sound is Coming From Wheels Inspection',
  'Clunking Noise When I Drive Over Bumps Inspection',
  'Clunking Or Knocking Noise From Wheels Inspection',
  'Clutch Fluid is Contaminated Inspection',
  'Clutch is Not Fully Disengaging Inspection',
  'Clutch is Not Working Inspection',
  'Coolant is Leaking Inspection',
  'Creaking Noise When Turning The Steering Wheel Inspection',
  'Cruise Control is Not Working Inspection',
  'Door Does Not Lock Or Open Inspection',
  'Engine Hesitates During Acceleration Inspection',
  'Engine Idle Speed is High Inspection',
  'Engine is Backfiring Inspection',
  'Engine is Making A Gurgling Sound Inspection',
  'Engine is Misfiring Inspection',
  'Engine is Running Louder Than Normal Inspection',
  'Engine is Shaking, Pulsating Or Vibrating Inspection',
  'Engine is Sputtering Inspection',
  'Engine Oil is Black and Gritty Inspection',
  'Excessive Car Bounce and Sway Inspection',
  'Exhaust Fume Odor In Car Inspection',
  'Fan Speed Control is Not Working Inspection',
  'Fog Or Driving Lights Are Not Working Inspection',
  "Fuel Door Won't Close Inspection",
  "Fuel Door Won't Open Inspection",
  'Fuel is Leaking From Gas Tank Inspection',
  "Gas Cap Won't Click Or Tighten Inspection",
  "Gas Cap Won't Come off Inspection",
  'Gas Pedal is Stuck Inspection',
  'Grease On Inner Edge of Tires Inspection',
  'Grinding Noise When Braking Inspection',
  'Grinding Noise While Shifting Inspection',
  'Headlight is Not Working Inspection',
  'Headlights Are Dim Inspection',
  'Headlights Do Not Change From Low To High Beam Inspection',
  'Heater is Not Working Inspection',
  'High Beam is Not Working Inspection',
  'Hissing Noise When Brake Pedal is Depressed Inspection',
  'Lights (Headlamps/Beams/Brakes) Inspection',
  'Loss of Power Inspection',
  'Loud Clicking Noise When I Turn The Car Inspection',
  'Loud Noise is Coming From Rear Brakes Inspection',
  'Loud Noise When Using The Clutch Inspection',
  'Loud Screeching Noise When I Start The Car Inspection',
  'Loud Squealing Or Rattling is Coming From Engine Inspection',
  'Noise From Engine Or Exhaust Inspection',
  'Oil Pressure Light is On Inspection',
  'Oil is Leaking Into Spark Plug Well Inspection',
  'Oil Level is Low Inspection',
  'Oil/Fluid Leak Inspection',
  'Parking / Emergency Brake Does Not Work Inspection',
  'Parking Brake is Stuck Inspection',
  'Parking Brake Light Stays On Inspection',
  "Parking Brake Won't Engage Inspection",
  "Parking Brake Won't Hold Car Inspection",
  "Parking Brake Won't Release Inspection",
  'Power Mirror is Not Working Inspection',
  'Power Outlet is Not Working Inspection',
  'Power Seat is Not Working Inspection',
  'Power Door Locks Are Not Working Inspection',
  'Power Steering Fluid is Brown Or Black Inspection',
  'Power Steering Fluid is Leaking Inspection',
  'Power Window is Noisy Inspection',
  'Rear Lights Are Not Working Inspection',
  'Reduced Power Light is On Inspection',
  'Reset Maintenance Reminder System',
  'Seat Vibrates Or Shakes Inspection',
  'Service Light is On Inspection',
  'Smell In The Car Inspection',
  'Smell of Oil In Car Inspection',
  'Smoke From Engine Or Exhaust Inspection',
  'Squealing Noise From Brakes Inspection',
  'Squealing Noise When Steering Wheel is Turned Inspection',
  'Steering Wheel Does Not Turn Car Inspection',
  'Steering Wheel Feels Loose Inspection',
  'Steering Wheel is Hard To Turn Inspection',
  'Temperature Warning Light is On Inspection',
  'Temperature Gauge is Maxed Out Inspection',
  'Traction Control Light is On Inspection',
  'Turn Signal Light is Not Working Inspection',
  'Valve Cover Gasket is Leaking Inspection',
  'Warning Light is On Inspection',
  'When I Slow Down and Stop The Car, Engine Shuts off Inspection',
  'Window Switch is Not Working Inspection',
  'Window Fell Inside The Door Inspection',
  'Window is Moving Up Or Down Very Slowly Inspection',
  'Window is Not Going Up Or Down Inspection',
  'Window is Not Working Inspection',
  'Windows Inspection',
  'Windshield Fogs Up Inspection',
  'Wipers Are Not Working Inspection',
  'Wipers Do Not Shut off Inspection',
  'Car Door Latch Replacement',
  'Car Door Lock Actuator Replacement',
  'Car Door Lock Relay Replacement',
  'Exterior Car Door Handle Replacement',
  'Hood Latch Replacement',
  'Hood Lift Support Shocks Replacement',
  'Interior Car Door Handle Replacement',
  'Lubricate Doors',
  'Lubricate Hood Hinge',
  'Lubricate Trunk',
  'Trunk Latch Release Cable Replacement',
  'Trunk Latch Replacement',
  'Trunk Lift Support Shocks Replacement',
  'Trunk Lock Actuator Replacement',
  'Throttle Cable Repair',
  'Air Bleed Housing Assembly Replacement',
  'Car Air Pump Check Valve Replacement',
  'Car Air Pump Replacement',
  'Automatic Shutdown Relay Replacement',
  'Barometric Sensor Replacement',
  'Car Battery Terminal Ends Replacement',
  'Camshaft Seal Replacement',
  'Coolant Recovery Reservoir Replacement',
  'Coolant Reservoir Replacement',
  'Coolant Temperature Switch (Sensor) Replacement',
  'Crankshaft Harmonic Balancer Replacement',
  'Cruise Control Cable Replacement',
  'Distributor O Ring Replacement',
  'Distributor Replacement',
  'Electronic Spark Control Replacement',
  'Engine or Transmission Mount Replacement',
  'Exhaust Gas Recirculation/EGR Valve Replacement',
  'Exhaust Manifold Gasket Replacement',
  'Exhaust Manifold Repair',
  'Fan Clutch Replacement',
  'Front Crankshaft Seal Replacement',
  'Car Heater Hoses Replacement',
  'Idle Control Valve Replacement',
  'Idler Pulley Replacement',
  'Intake Manifold Gaskets Replacement',
  'Intake Manifold Runner Control Replacement',
  'Manifold Absolute Pressure Sensor (MAP Sensor) Replacement',
  'Oil Cooler Adapter Gasket Replacement',
  'Oil Cooler Hose (Automatic Transmission) Replacement',
  'Oil Cooler Lines Replacement',
  'Oil Cooler Repair',
  'Oil Filter Housing Gasket Replacement',
  'Oil Pan Gasket Replacement',
  'Oil Pan Replacement',
  'Oil Pressure Sensor Replacement',
  'PCV Valve Hose Replacement',
  'Positive Crankcase Ventilation (PCV) Valve Replacement',
  'Power Steering Belt Replacement',
  'Serpentine/Drive Belt Replacement',
  'Supercharger Belt Replacement',
  'Car Thermostat Replacement',
  'Throttle Body Replacement',
  'Throttle Cable Replacement',
  'Throttle Controller Replacement',
  'Valve Cover Gasket Replacement',
  'Variable Valve Timing (VVT) Solenoid Replacement',
  'Variable Valve Timing (VVT) Switch Replacement',
  'Vent Oil Separator Replacement',
  'Auxiliary Water Pump Replacement',
  'Water Pump Pulley Replacement',
  'Water Pump Replacement',
  'Windshield Washer Reservoir Replacement',
  'Canister Purge Solenoid Replacement',
  'EVP Position Sensor Replacement',
  'Evaporation Vent Solenoid Replacement',
  'Evaporative Emission Control Canister Replacement',
  'Evaporator Temperature Sensor (Switch) Replacement',
  'Car Engine Air Filter Replacement',
  'Cabin Air Filter Replacement',
  'Fuel Filter Replacement',
  'Brake System Drain/Refill',
  'Engine Oil Change',
  'Car Radiator Replacement',
  'Cooling System Drain/Refill',
  'Power Steering Fluid Drain/Refill',
  'Radiator Drain/Refill',
  'Cooling/Radiator Fan Motor Replacement',
  'Pressure Test Radiator Cap',
  'Carburetor Replacement',
  'Fuel Filler Cap Replacement',
  'Fuel Gauge Sender Replacement',
  'Fuel Injector O Rings Replacement',
  'Fuel Injector Replacement',
  'Fuel Pressure Regulator Replacement',
  'Fuel Pressure Sensor Replacement',
  'Fuel Pump Replacement',
  'Gas Cap Replacement',
  'Injector Control Pressure Sensor Replacement',
  'Car AC Compressor Relay Replacement',
  'Blower Motor Relay Replacement',
  'Blower Motor Switch Replacement',
  'Condenser Fan Relay Replacement',
  'Expansion Valve (Orifice Tube) Replacement',
  'Car Heater Blower Motor Replacement',
  'Car Heater Blower Motor Resistor Replacement',
  'Car Heater Control Valve Replacement',
  'Air Injection Hose Replacement',
  'Brake Hose Replacement',
  'Exhaust Gas Recirculation (EGR) Tube Replacement',
  'Car Heater Bypass Tube Replacement',
  'Upper Radiator Hose Replacement',
  'Lower Radiator Hose Replacement',
  'Ballast Resistor Replacement',
  'Distributor Cap and Rotor Replacement',
  'Ignition Cable (Spark Plug Wires) Replacement',
  'Ignition Coil Replacement',
  'Replace Starter',
  'Spark Plug Replacement',
  'Brake Light Bulb Replacement',
  'Brake Light Switch Replacement',
  'Console Light Bulb Replacement',
  'Courtesy Light Bulb Replacement',
  'Car Dome Light Bulb Replacement',
  'Fog Light Relay Replacement',
  'Fog/Driving Light Bulb Replacement',
  'Hazard / Turn Signal Flasher Replacement',
  'Headlight Bulb Replacement (Low Beam)',
  'Headlight Bulb Replacement (High Beam)',
  'License Plate Light Replacement',
  'Reset Indicator Lights',
  'Reverse Light Bulb Replacement',
  'Tail Light Bulb Replacement',
  'Tail Light Assembly Replacement',
  'Trunk Light Bulb Replacement',
  'Turn Signal Bulb Replacement',
  'Car Door Mirror Replacement',
  'Abs Speed Sensor Replacement',
  'Air Charge Temperature Sensor Replacement',
  'Air Cleaner Temperature Sensor Replacement',
  'Camshaft Position Sensor Replacement',
  'Coolant Level Sensor Replacement',
  'Crankshaft Position Sensor Replacement',
  'Intermittent Wiper Relay Replacement',
  'Low Water Sensor Replacement',
  'Manifold Temperature Sensor Replacement',
  'Mass Airflow Sensor Replacement',
  'Oil Temperature Sensor Replacement',
  'Oxygen Sensor Replacement',
  'Throttle Position Sensor (Tps) Replacement',
  'Throttle/Accelerator Pedal Position Sensor Replacement',
  'Top Dead Center (Tdc) Sensor Replacement',
  'Wheel Speed Sensor Replacement',
  'Yaw Rate Sensor Replacement',
  'Cv Axle / Shaft Assembly Replacement (Driver Side)',
  'Cv Axle / Shaft Assembly Replacement (Passenger Side)',
  'Ball Joint Replacement (Front Passenger Side)',
  'Ball Join Replacement (Front Driver Side)',
  'Ball Joint Replacement (Rear Passenger Side)',
  'Ball Joint Replacement (Rear Driver Side)',
  'Center (Drag) Link Replacement',
  'Front Control Arm Assembly Replacement (Left Lower)',
  'Front Control Arm Assembly Replacement (Left Upper)',
  'Front Control Arm Assembly Replacement (Right Lower)',
  'Front Control Arm Assembly Replacement (Right Upper)',
  'Rear Control Arm Assembly Replacement (Left Lower)',
  'Rear Control Arm Assembly Replacement (Left Upper)',
  'Rear Control Arm Assembly Replacement (Right Lower)',
  'Rear Control Arm Assembly Replacement (Right Upper)',
  'Differential/Gear Oil Replacement',
  'Differential Fluid Service Replacement',
  'Drag Link Replacement',
  'Lateral Link Replacement',
  'Lubricate Ball Joints',
  'Lubricate Steering and Suspension',
  'Lubricate Suspension',
  'Lubricate U Joints',
  'Pitman Arm Replacement',
  'Power Steering Fluid Reservoir Replacement',
  'Power Steering Input Shaft Seal Replacement',
  'Power Steering Pressure Hose Replacement',
  'Power Steering Pressure Switch Replacement',
  'Power Steering Pump Pulley Replacement',
  'Power Steering Pump Replacement',
  'Front Shock Absorber Replacement (One Side)',
  'Front Shock Absorber Replacement (Both Sides)',
  'Rear Shock Absorber Replacement (One Side)',
  'Rear Shock Absorber Replacement (Both Sides)',
  'Front & Rear Shock Absorber Replacement (Both Sides)',
  'Stabilizer Bar Bushings Replacement',
  'Stabilizer Bar Links Replacement',
  'Steering Damper Replacement',
  'Steering Stabilizer Stop Replacement',
  'Front Strut Assembly Replacement (Driver Side)',
  'Front Strut Assembly Replacement (Passenger Side)',
  'Front Strut Assembly Replacement (Both Sides)',
  'Rear Strut Assembly Replacement (Driver Side)',
  'Rear Strut Assembly Replacement (Passenger Side)',
  'Rear Strut Assembly Replacement (Both Sides)',
  'Front & Rear Strut Assembly Replacement (Both Sides)',
  'Sway Bar Replacement',
  'Tie Rod End Replacement (Front Left Inner)',
  'Tie Rod End Replacement (Front Left Outer)',
  'Tie Rod End Replacement (Front Right Inner)',
  'Tie Rod End Replacement (Front Right Outer)',
  'Tie Rod End Replacement (Rear Left Inner)',
  'Tie Rod End Replacement (Rear Left Outer)',
  'Tie Rod End Replacement (Rear Right Inner)',
  'Tie Rod End Replacement (Rear Right Outer)',
  'Tighten Wheel Lug Nuts',
  'Track Bar Replacement',
  'Universal Joint (U Joint) Replacement',
  'Wheel/Hub Bearings Replacement (Front Left)',
  'Wheel/Hub Bearings Replacement (Front Right)',
  'Wheel/Hub Bearings Replacement (Rear Left)',
  'Wheel/Hub Bearings Replacement (Rear Right)',
  'Wheel Stud Replacement',
  'Reverse Lights Switch Replacement',
  'Clutch Safety Switch Replacement',
  'Clutch Switch Replacement',
  'Car Door Lock Switch Replacement',
  'Headlight Switch Replacement',
  'Neutral Safety Switch Replacement',
  'Power Seat Switch Repair',
  'Power Window Switch Repair',
  'Turn Signal Switch Replacement',
  'Power Window Switch Repair (Front Left)',
  'Power Window Switch Repair (Front Right)',
  'Power Window Switch Repair (Right Left)',
  'Power Window Switch Repair (Right Rear)',
  'Window Motor Regulator Replacement (Front Left)',
  'Window Motor Regulator Replacement (Front Right)',
  'Window Motor Regulator Replacement (Right Left)',
  'Window Motor Regulator Replacement (Right Right)',
  'Clean Windshield Washer Tubes and Jets Inspection',
  'Washer Fluid Does Not Spray Onto Windshield Inspection',
  'Window Motor Regulator Replacement',
  'Windshield Washer Pump Replacement',
  'Windshield Wiper Arm Replacement',
  'Windshield Wiper Blade Replacement',
  'Windshield Wiper Linkage Replacement',
  'Windshield Wiper Motor Replacement',
  'Windshield Wiper Refill Replacement',
  'Windshield Wiper Switch Replacement',
  'Windshield Wiper/Washer System Inspection',
  'Wiper Gearbox Replacement',
];
